#!/bin/sh
# Regenerates /etc/qubes/policy.d/30-qrexec-tcp-bridge.policy from every
# fragment in /etc/qrexec-tcp-bridge/access.conf.d/*.conf.
#
# Run on dom0 only -- qrexec policy is always dom0-side, regardless of
# which qube local.ConnectTCP itself is installed on. No-op (silently
# skipped) on a regular qube, where policy.d doesn't apply anyway.
#
# Re-run manually after adding/editing a fragment -- this isn't
# triggered automatically by editing the conf.d directory itself, only
# by (re)installing a package whose %post calls this script.
#
# Each fragment line is "origin_tag destination port":
#   devel gitea-forge-host 3000
#
# OR semantics: either tag alone is sufficient, on either side. A qube
# carrying "devel" may call local.ConnectTCP+3000 against ANY qube
# (not only ones tagged gitea-forge-host); a qube carrying
# "gitea-forge-host" may be called by ANY qube on that port (not only
# ones tagged devel). The two tags are not a matched pair that both
# have to hold at once -- each is independently sufficient. This is
# broader than a same-line-both-sides-must-match whitelist: tagging a
# qube "devel" grants it that port against everyone, and tagging a
# qube "gitea-forge-host" opens that port on it to everyone, not just
# to each other specifically.
#
# Expands to 4 lines per tag-based fragment (one for each tag as
# source-side-open, one for each tag as destination-side-open) --
# Qubes RPC Policy 4.0 has no OR combinator within a single
# source/destination field, so this is the only way to express it.
#
# EXCEPT the literal string "dom0" on the destination side, which is
# emitted as a single, unexpanded "origin_tag -> dom0" line (source
# must carry origin_tag; dest is fixed dom0, not opened to @anyvm) --
# dom0 does not participate in the OR pool as a taggable destination:
# whether dom0 itself can even carry a qvm-tag is unverified from this
# package's development environment (no live qubesd to check against),
# and "anyone may reach dom0 on this port" is not something to expand
# into automatically regardless. Literal "dom0" is the same syntax
# qubes-rpc-user's own pre-factoring policy already used.
set -eu

CONFD=/etc/qrexec-tcp-bridge/access.conf.d
OUT=/etc/qubes/policy.d/30-qrexec-tcp-bridge.policy

# qubesd (the admin daemon) only ever runs on dom0 -- unlike /etc/qubes,
# which may exist more broadly. Unverified against a real dom0 either
# way (no live system to check this heuristic against); if it turns out
# wrong, fix here rather than assuming every consumer's %post got it
# right independently.
command -v qubesd >/dev/null 2>&1 || { echo "generate-policy.sh: qubesd not present, not dom0, skipping" >&2; exit 0; }

{
    echo "## Generated by qrexec-tcp-bridge's generate-policy.sh from"
    echo "## ${CONFD}/*.conf -- do not edit by hand, edit a fragment there"
    echo "## and re-run generate-policy.sh instead."
    echo "##"
    echo "## OR semantics: either tag alone is sufficient (not a matched"
    echo "## pair) -- see the comment at the top of generate-policy.sh."
    echo "##"
    for f in "${CONFD}"/*.conf; do
        [ -e "$f" ] || continue
        echo "## from $(basename "$f")"
        while read -r origin dest port; do
            case "$origin" in ''|'#'*) continue ;; esac
            if [ "$dest" = "dom0" ]; then
                echo "local.ConnectTCP +${port} @tag:${origin} dom0 allow"
            else
                echo "local.ConnectTCP +${port} @tag:${origin} @anyvm allow"
                echo "local.ConnectTCP +${port} @anyvm @tag:${origin} allow"
                echo "local.ConnectTCP +${port} @tag:${dest} @anyvm allow"
                echo "local.ConnectTCP +${port} @anyvm @tag:${dest} allow"
            fi
        done < "$f"
    done
    echo "local.ConnectTCP * @anyvm @anyvm deny"
} > "$OUT"

echo "generate-policy.sh: wrote $OUT"
