#!/bin/sh
# Regenerates /etc/qubes/policy.d/30-qrexec-tcp-bridge.policy from every
# fragment in /etc/qrexec-tcp-bridge/access.conf.d/*.conf.
#
# Run on dom0 only -- qrexec policy is always dom0-side, regardless of
# which qube local.ConnectTCP itself is installed on. No-op (silently
# skipped) on a regular qube, where policy.d doesn't apply anyway.
#
# Re-run manually after adding/editing a fragment -- this isn't
# triggered automatically by editing the conf.d directory itself, only
# by (re)installing a package whose %post calls this script.
#
# Each fragment line is "origin_tag destination port":
#   devel gitea-forge-host 3000
# allows qubes tagged "devel" to call local.ConnectTCP+3000 against
# qubes tagged "gitea-forge-host". Both sides are Qubes RPC Policy 4.0
# @tag: references (natively supported on either side of a policy
# line -- unlike qvm-firewall, which only takes a literal VM name, no
# per-qube enumeration is needed here), EXCEPT the literal string
# "dom0" on the destination side, which is emitted as-is (unquoted
# "dom0", not "@tag:dom0") -- whether dom0 itself can even carry a
# qvm-tag is unverified from this package's development environment
# (no live qubesd to check against), whereas literal "dom0" as a qrexec
# policy destination is the same syntax qubes-rpc-user's own
# pre-factoring policy already used.
set -eu

CONFD=/etc/qrexec-tcp-bridge/access.conf.d
OUT=/etc/qubes/policy.d/30-qrexec-tcp-bridge.policy

# qubesd (the admin daemon) only ever runs on dom0 -- unlike /etc/qubes,
# which may exist more broadly. Unverified against a real dom0 either
# way (no live system to check this heuristic against); if it turns out
# wrong, fix here rather than assuming every consumer's %post got it
# right independently.
command -v qubesd >/dev/null 2>&1 || { echo "generate-policy.sh: qubesd not present, not dom0, skipping" >&2; exit 0; }

{
    echo "## Generated by qrexec-tcp-bridge's generate-policy.sh from"
    echo "## ${CONFD}/*.conf -- do not edit by hand, edit a fragment there"
    echo "## and re-run generate-policy.sh instead."
    echo "##"
    for f in "${CONFD}"/*.conf; do
        [ -e "$f" ] || continue
        echo "## from $(basename "$f")"
        while read -r origin dest port; do
            case "$origin" in ''|'#'*) continue ;; esac
            if [ "$dest" = "dom0" ]; then
                dest_token="dom0"
            else
                dest_token="@tag:${dest}"
            fi
            echo "local.ConnectTCP +${port} @tag:${origin} ${dest_token} allow"
        done < "$f"
    done
    echo "local.ConnectTCP * @anyvm @anyvm deny"
} > "$OUT"

echo "generate-policy.sh: wrote $OUT"
